# Generated by Django 5.2.9 on 2026-01-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_newitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Ключ')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('page', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Редактируемый контент',
                'verbose_name_plural': 'Редактируемый контент',
                'ordering': ['page', 'key'],
            },
        ),
    ]
